### ISSUE TITLE
White screen when starting chroma_controller.py relatively.

### ISSUE THREAD

**Issue by lah7** [lah7/razer_blackwidow_chroma_gui#11]
Since the large changes made in 959fe10d660dc0d5630f334427ed7bf732c1f8be, there's now a problem trying to run the Chroma Controller GUI with a relative path. No errors appear in the terminal.

For instance, there is a white screen when executing a relative path:
`./gui/chroma_controller/chroma_controller.py`

But it runs fine when executing with an absolute path:
`/usr/share/razer_chroma_controller/chroma_controller.py`

I suspect it's how the new changes are determining the location of the files.

**Comment by lah7** [comment]
Confirmed: https://github.com/pez2001/razer_blackwidow_chroma_driver/issues/49#issuecomment-171253833

**Comment by terrycain** [comment]
Fixed in latest pull request.

It seems webkit refuses to load HTML with relative paths.

**Comment by lah7** [comment]
Thanks. Fixed in 51dee1c2f44478479579b3f3cebc8b17ff5bed5a
