### ISSUE TITLE
Abandoned new profiles remain in list.

### ISSUE THREAD

**Issue by lah7** [lah7/razer_blackwidow_chroma_gui#13]
Minor bug found. To reproduce:

1. Create a new profile, call it anything.
2. Click **Cancel** to return to the main menu.
3. The new profile is listed, but it doesn't exist, causing errors when attempting to edit or delete.

**Comment by terrycain** [comment]
Have seen, working on it

**Comment by lah7** [comment]
Fixed in d91f3d23e7523b24a9707576a7525899f43e31d1
