### ISSUE TITLE
Tray Applet - Set profiles from tray

### ISSUE THREAD

**Issue by lah7** [lah7/razer_blackwidow_chroma_gui#14]
Sounds simple, but will require migrating the `ChromaProfiles` class to its own module. Some variables tied to `chroma_controller.py` like paths (`SAVE_ROOT` and `SAVE_PROFILES`) should be shared between them where possible to avoid duplication.

Leaving feature request here as a public reminder.

**Comment by terrycain** [comment]
Was already thinking of moving ChromaProfiles to the razer module ;)

**Comment by lah7** [comment]
Migrated classes to modules: 05c610de373247bf875c2ecabe2a7ab67d8b2dc3
Add profiles menu to tray: 344a2693db7d59f8c3bad079a304d091ce17fb5f

Although the code for the profile menu isn't perfect, it works. We can clean up and correct it later.

**Comment by terrycain** [comment]
Nice
