### ISSUE TITLE
Tray Applet - Ability to switch profiles

### ISSUE THREAD

**Issue by lah7** [lah7/razer_blackwidow_chroma_gui#2]
Add a sub-menu so it is possible to use and activate existing profiles from `~/.config/razer_chroma` for quick switching.

----
This requires #1 to be addressed first.

**Comment by terrycain** [comment]
Hope you dont mind me commenting on all of the issues ;)

Activating them *shouldn't* be too difficult. We could move ChromaProfile to the razer library somewhere and then just use that and it should do it all nicely. The difficult bit would be somehow informing the chroma-controller when its ran what profile is active.

**Comment by lah7** [comment]
Don't worry, think of this fork as being solely focused on the GUI of things. You could push experimental code here if you want me to test and report on them before they go upstream.

----
While you're definitely faster at coding then me, I too was thinking that the Profiles class should be a module of its own. Solely since this allows other scripts and the Tray Applet can make use of profiles.

Is it possible for the daemon to store text in memory? That could be one way to "remember" what's active. My other suggestion would be a temporary file, such as  `/tmp/.razer_active`.

**Comment by lah7** [comment]
Oops. Same as #14.
