### ISSUE TITLE
Tray Applet - Custom Tray Icon

### ISSUE THREAD

**Issue by lah7** [lah7/razer_blackwidow_chroma_gui#5]
If a user wants the program to integrate better with the rest of their system in their system tray, then there should be able to place a custom image file or icon name (eg. `preferences-keyboard`) as an override for the default icon.

------

In addition, there could be a feature where the tray icon changes colour depending on the current primary colour.

**Comment by terrycain** [comment]
Not a bad shout. First option easily doable, will add that later, basically it'll just check for a user supplied file in `~/.config` somewhere.

2nd option, would be nice, but I think that would require an image per colour which as they can be custom is infinite images. We could create them on the fly but is it really necessary?

Now if we had an app for the mouse, it would be useful to change it based on battery level.

**Comment by lah7** [comment]
The original suggestion is good to me, best to keep resource usage down.

------
About the mouse part, we *could* re-organise the program and have interfaces for more then just the BlackWidow Chroma. It'll just be like an open source Syanpse.

**Comment by terrycain** [comment]
I am liking the idea of an open source version of synapse. Yes making it support multiple devices would be good as I also have a firefly which we should add too.

**Comment by lah7** [comment]
Back to this, we could use `preferences.json` from the config folder `~/.config/razer_chroma` to determine a custom pathname. Single names like `ibus-keyboard` work too (`/usr/share/icons/ubuntu-mono-dark/status/22/ibus-keyboard.svg` in Ubuntu).

Preferences could then be added to the GUI Chroma for specifying - like:
 * **Default** - (Linux drivers logo)
 * **System** - (`ibus-keyboard`)
 * **Custom** - (Filename)

**Comment by terrycain** [comment]
We should make a class which deals with the `preferences.json` then we could just call something like `get_icon_pathname()`

**Comment by lah7** [comment]
Added custom tray icons in 413f2139bb9642cd85238ff7881f34c2646035d8, even an animated variant in 3993e1b683277a2b1117ebdf0d03b561fe730bab.

**Comment by terrycain** [comment]
I like the sound of animated. Would be useful when I add battery for the mamba
