### ISSUE TITLE
Profiles list not refreshing after deletion.

### ISSUE THREAD

**Issue by lah7** [lah7/razer_blackwidow_chroma_gui#9]
Terminal outputs:
`Forcing refresh of profiles list...`

Expecting list to refresh but it doesn't seem to do so.

**Comment by terrycain** [comment]
Can you reproduce this and if so, how?

**Comment by lah7** [comment]
From testing the changes on my system yesterday:
 * Create a new profile, highlight a few keys.
 * Save the profile, return to main menu.
 * Delete the profile.

`Forcing refresh of profiles` appears in the terminal, but the actual list isn't updated, thus causes a potential crash when trying to delete again or editing a non existent file.

I haven't taken a closer look yet, I know you'll beat me to it :wink:

**Comment by terrycain** [comment]
Working on it

**Comment by lah7** [comment]
Thanks for that, working again. :+1:  Fixed in 0671deb759ac6effe56cb1720fef553cd1243b71
